AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /time
            Method: GET

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      Runtime: nodejs4.3
      Environment:
        Variables:
          ISPRODUCTION: "0"
          DEBUGE: "0"
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /test
            Method: GET
